version: "2.1"

networks:
  default:
    external: true
    name: testing_network

services:
  mysql:
    image: percona:latest
    ports:
      - "3306:3306"
    volumes:
      - "./init/mysql-init.sql:/docker-entrypoint-initdb.d/1.sql"
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ['CMD', 'mysqladmin', '-utest_qa', '-pqa_test', 'ping', '-h', '127.0.0.1']
      interval: 3s
      retries: 30

  test_app:
    image: myapp
    command: bash -c '/app/wait_for_mock.sh; /app/myapp --config=/app/app-config' # --setup
    ports:
      - "8081:8081"
    volumes:
      - "./init/wait_for_mock.sh:/app/wait_for_mock.sh"
      - "./init/app-config:/app/app-config"
    depends_on:
      mysql:
        condition: service_healthy
      selenoid:
        condition: service_started

  vk_mock:
    image: vk_mock
    build:
      context: ./mock
    ports:
      - "8090:8090"
    environment:
      MOCK_HOST: '0.0.0.0'
      MOCK_PORT: '8090'

  selenoid:
    image: aerokube/selenoid:1.10.3
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "./init/browsers.json:/selenoid/browsers.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-conf", "/selenoid/browsers.json"]

  selenoid-ui:
    links:
      - selenoid
    image: aerokube/selenoid-ui:latest
    network_mode: bridge
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
