version: "2.1"
services:
  mysql:
    image: percona:latest
    ports:
      - "3306:3306"
    volumes:
      - ./init/mysql-init.sql:/docker-entrypoint-initdb.d/1.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ['CMD', 'mysqladmin', '-utest_qa', '-pqa_test', 'ping', '-h', '127.0.0.1']
      timeout: 2s
      retries: 30

  test_app:
    image: myapp
    command: /app/myapp --config=/app/app-config # --setup
    ports:
      - "8080:8080"
    volumes:
      - ./init/app-config:/app/app-config
    depends_on:
      mysql:
        condition: service_healthy